{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "callcenter-ai.serviceAccountName" . }}-agent
  labels:
    {{- include "callcenter-ai.agentService.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "callcenter-ai.serviceAccountName" . }}-tfidf
  labels:
    {{- include "callcenter-ai.tfidfService.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "callcenter-ai.serviceAccountName" . }}-transformer
  labels:
    {{- include "callcenter-ai.transformerService.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "callcenter-ai.serviceAccountName" . }}-mlflow
  labels:
    {{- include "callcenter-ai.mlflow.labels" . | nindent 4 }}
{{- end }}